<?php $config = array (
  'domain' => 'animemanito.tv',
  'urlpath' => 'https://animemanito.tv',
  'cdnpath' => 'https://animemanito.tv/cdn',
  'adminpath' => 'https://animemanito.tv/panel',
  'site_name' => 'AnimeManito',
  'facebook' => 'https://facebook.com/',
  'youtube' => '',
  'media_folder' => 'animes',
  'theme' => 'animemanito',
  'facebook_appid' => '',
  'facebook_appsecret' => '',
  'recaptcha_key' => '6Lcr_egiAAAAAM0LgZoqnUbHyJAH0cBAlanilFO7',
  'recaptcha_secret' => '6Lcr_egiAAAAAMaE4MQS3Tn-dHYKoBKR98EppS7n',
  'analytics' => 'UA-149261571-1',
);