<?php $config = array (
  'domain' => 'animefenix.tv',
  'urlpath' => 'https://animefenix.tv',
  'cdnpath' => 'https://animefenix.tv/cdn',
  'adminpath' => 'https://animefenix.tv/panel',
  'site_name' => 'AnimeFénix',
  'facebook' => 'https://facebook.com/Untaltioyt-105493257589307',
  'youtube' => '',
  'media_folder' => 'animes',
  'theme' => 'animefenix-frans185',
  'facebook_appid' => '',
  'facebook_appsecret' => '',
  'recaptcha_key' => '6Lcr_egiAAAAAM0LgZoqnUbHyJAH0cBAlanilFO7',
  'recaptcha_secret' => '6Lcr_egiAAAAAMaE4MQS3Tn-dHYKoBKR98EppS7n',
  'analytics' => 'UA-149261571-1',
);